config/routes.rb
Calendar::Application.routes.draw do
  resources :companies

  resources :events

  root "posts#index"
  resources :posts
  get "full_calendar" => "posts#full_calendar"
  get "calendar_helper" => "posts#calendar_helper"
  mount Ckeditor::Engine => "/ckeditor"

  

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  validates_attachment_size :data, :less_than => 100.megabytes
  validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :styles => { :content => '800>', :thumb => '118x100#' }

  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  
  
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render action: 'show', status: :created, location: @company }
      else
        format.html { render action: 'new' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :description)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :body, :start, :end)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
      @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  def full_calendar
    @wow = Schedule.first
    if params[:start] and params[:end]
      start_time = Time.at(params[:start].to_i).to_datetime
      end_time = Time.at(params[:end].to_i).to_datetime
      @posts = Post.where(:start => start_time..end_time)
    end

    @post = Post.new
    respond_to do |format|
      format.html
      format.json
    end
  end

  def calendar_helper
    @posts = Post.all
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :start, :end)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/companies/_form.html.haml
= simple_form_for(@company) do |f|
  %div
    = f.error_notification
  .form-inputs.form-group
    = f.input :name,:input_html => { :rows => 10, :class => "form-control" }, placeholder:"fill in company name", required: true
    = f.input :description, :value => "Default value", :id => "sometext",:input_html => { :rows => 10, :class => "form-control" }, placeholder:"company description", required: true
  .form-actions.form-group
    = f.button :submit, class:"btn btn-success"

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/index.html.haml
%div
= link_to 'New Company', new_company_path, class:"btn btn-success pull-right"
%h1 Listing companies
%div
- @companies.each do |company|
    %h3= company.name
    %div= company.description
    %div.well
        = link_to 'Show', company, class:"btn btn-link"
        = link_to 'Edit', edit_company_path(company), class:"btn btn-link"
        = link_to 'Destroy', company, :method => :delete, :data => { :confirm => 'Are you sure?' }, class:"btn btn-link"

%br

app/views/companies/new.html.haml
= link_to 'Back', companies_path, class:"btn btn-default"
%h1 New company
= render 'form'

app/views/companies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @company.name
%p
  %b Description:
  = @company.description

= link_to 'Edit', edit_company_path(@company)
\|
= link_to 'Back', companies_path

app/views/events/_form.html.haml
= simple_form_for(@event) do |f|
  = f.error_notification
  .field.form-group
    = f.input :title
    = f.input :body, :input_html => { :rows => 10 }
    = f.input :start, :input_html => { class:"datepicker form-control" },
          :as => :string, :dateFormat => "mm-dd-yy"
    = f.input :end, :input_html => { class:"timepicker form-control" },
          :as => :string

  .form-actions.form-group
    = f.button :submit, class:"btn btn-success"
  :javascript
    $('#datetimepicker').datetimepicker({
      format: 'dd/MM/yyyy hh:mm:ss',
      language: 'pt-BR'
    });

    $('.datepicker').datepicker({ 
        dateFormat: "yy-mm-dd" }
      );

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
= link_to 'New Event', new_event_path, class:"pull-right btn btn-primary col-lg-2"

%h1 Listing events

%table.table.table-striped.table-bordered
  %tr.danger
    %th Title
    %th Body
    %th Start at
    %th End at
    %th
    %th
    %th

  - @events.each do |event|
    %tr
      %td= event.title
      %td= event.body
      %td= event.start
      %td= event.end
      %td= link_to 'Show', event
      %td= link_to 'Edit', edit_event_path(event)
      %td= link_to 'Destroy', event, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @event.title
%p
  %b Body:
  = @event.body
%p
  %b Start at:
  = @event.start
%p
  %b End at:
  = @event.end

= link_to 'Edit', edit_event_path(@event)
\|
= link_to 'Back', events_path

app/views/layouts/_nav.html.erb
<div class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
  <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Project name", root_path, class:"navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to 'Posts', posts_path %></li>
            <li><%= link_to 'Company profile', companies_path %></li>
            <li><%= link_to 'Full Calendar', full_calendar_path %></li>
            <li><%= link_to 'Calendar Helper', calendar_helper_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calendar</title>
  <!--[if lt IE 8]>
    <%= stylesheet_link_tag "font-awesome-ie7.min.css", media: "all" %>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "application-print", :media => "print" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/nav" %>
  <div class="container">
    <div style="min-height:100px;"></div>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.haml
%div.well
  = simple_form_for @post, defaults: { input_html: { class: 'form-control' } }  do |f|
    - if @post.errors.any?
      #error_explanation
        %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
        %ul
          - @post.errors.full_messages.each do |msg|
            %li= msg

    .field.form-group
      = f.input :title, required:true
    .field.form-group
      = f.input :body, :value => "Default value", :id => "sometext",:input_html => { :rows => 5 }, required: true
    .field.form-group
      = f.input :start, :input_html => { class:"datepicker form-control" }, placeholder:"select start date", :as => :string, :dateFormat => "mm-dd-yy", required:true
    .field.form-group
      = f.input :end, :input_html => { class:"datepicker form-control", :dateformat => "mm-dd-yy" }, placeholder:"select end date", :as => :string, required: true
    .actions.form-group
      = f.button :submit, 'save', class:"btn btn-success btn-block"

      :javascript
          $('.datepicker').datepicker({ 
            dateFormat: "yy-mm-dd" }
          );

          $('#post_start').attr("readOnly", true);
          $('#post_end').attr("readOnly", true);

app/views/posts/_open_hour_form.html.haml
%div.container
  %div
    %label Monday
    %input.start_time  to  
    %input.end_time
    %button.addbutton Add time
  %div
    %label Tuesday
    %input.start_time  to  
    %input.end_time
  %div
    %label Wednesday
    %input.start_time  to  
    %input.end_time
  %div
    %label Thursday
    %input.start_time  to  
    %input.end_time

app/views/posts/calendar_helper.html.haml
%div.calendar
      = calendar({:year => 2013, :month => 10})

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/full_calendar.html.haml
= @wow.inspect
%div#calendar-modal.modal.fade{:hidden=>true}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{"data-dismiss" => "modal", "aria-hidden" => true} &times;
        %h4.modal-title 
          %strong Configure Opening Hours 
      %div.modal-body
        %h5 Please configure your business hours
        = render "open_hour_form"

      %div.modal-footer
        %button.btn.btn-success Save change

%div.col-md-3
  %div.well
    %button#working-hour.btn.btn-primary.btn-block
      Configure Opening Hours
    %div.space
    %h4 Open Hours
    %table
      %tr.space
        %td 
          %strong Monday
        %td 08:00AM-11:30PM
      %tr.space
        %td
        %td 01:00PM-05:00PM
      %tr
        %td 
          %strong Tuesday
        %td Closed
      %tr
        %td
        %td 01:00PM-05:00PM
      %tr
        %td 
          %strong Wednesday
        %td 08:00AM-11:30PM
      %tr
        %td
        %td 01:00PM-05:00PM


%div.col-md-9
  %div.calendar-wrapper
    %div#calendar
      %div#modal.modal.fade{:hidden=>true}
        %div.modal-dialog
          %div.modal-content
            %div.modal-header
              %button.close{"data-dismiss" => "modal", "aria-hidden" => true} &times;
              %h4.modal-title Create New Event
            %div.modal-body
              = render "form"
:javascript

      // defined instance of the dialog
      // $( "#dialog" ).dialog( { 
      //     autoOpen: false, 
      //     title: "Input Holiday"
      //     });
      // user click, the
      var calendar = $('#calendar').fullCalendar({
          header: {
            right: "prev,next, today",
            center: "title",
            left: "month,agendaWeek,agendaDay"
          },

          selectHelper: true,
          selectable: true,
          editable: true,
          events: {
            url: 'https://www.google.com/calendar/feeds/en.cambodian%23holiday%40group.v.calendar.google.com/public/basic'
          },
          select: function(start, end, allDay) {
            $('#modal').modal();
            /* if title is enterd calendar will add title and event into fullCalendar.*/
            if (title) {
              calendar.fullCalendar('renderEvent',
                {
                  title: title,
                  start: start,
                  end: end,
                  allDay: allDay
                },
              true // make the event "stick"
            );
            }
            calendar.fullCalendar('unselect');
          },
          eventSources: [{
            url: "/full_calendar",
            allDay: true
          }],
          dayClick: function() {
            $('#modal').modal({
            });
          },
          height: 600,
      });

      $("#working-hour").click(function() {
        $("#calendar-modal").modal();
      });

app/views/posts/index.html.haml
= link_to 'New Post', new_post_path, class:"pull-right btn btn-primary col-lg-2"
%h1 Listing posts
%table.table.table-striped.table-bordered
  %tr.danger
    %th Title
    %th Body
    %th Start date
    %th End date
    %th
    %th
    %th

  - @posts.each do |post|
    %tr
      %td= post.title
      %td= post.body
      %td= post.start
      %td= post.end
      %td= link_to 'Show', post
      %td= link_to 'Edit', edit_post_path(post)
      %td= link_to 'Destroy', post, :method => :delete, :data => { :confirm => 'Are you sure?' }

  %br
  :javascript
    var obj = #{ @posts.to_json }

app/views/posts/new.html.haml
%div
  = link_to 'Back', posts_path, class:"btn btn-default"
%div
  %h1 New post
  = render 'form'

app/views/posts/show.html.haml
%p#notice= notice

%div.btn-group.col-md-12
  = link_to 'Back', posts_path, class:"btn btn-primary"
  = link_to 'Edit', edit_post_path(@post), class:"btn btn-primary"

%div.col-md-12.well
  %p
    %b Title:
    = @post.title
  %p
    %b Body:
    = @post.body
  %p
    %b Start date:
    = @post.start
  %p
    %b End date:
    = @post.end